
version: '3.8'
services:
  backend:
    image: ttrl-app-backend
    ports:
     - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      AWS_REGION: ${AWS_REGION}
      COGNITO_APP_CLIENT_ID: ${COGNITO_APP_CLIENT_ID}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
