version: "3.8"

services:
  cloudbeaver:
      image: dbeaver/cloudbeaver:23.2.1
      container_name: dbeaver
      restart: always
      ports:
       - 8978:8978
      volumes:
       - cloudbeaver:/opt/cloudbeaver/workspace

volumes:
  cloudbeaver:
